D:/CodeBlocksProjects/Solver/findRoots.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <locale.h>
#include <cassert>
#include <cmath>
#include "findRoots.h"
Functions
coef makeCoef (float a, float b, float c)
roots makeRoots (int num, float x1, float x2, float comp)
int compare (float a, float b)
void rootsOrder (roots *myRoots)
roots findLinear (coef quatr)
roots solveQuadratic (coef quatr)
roots findRoots (struct coef quatr)
Detailed Description
Quadratic equvals Solver
Definition in file findRoots.cpp.
Function Documentation
compare()
int compare (float a, float b)
Compare two numbers
Parameters
a First number
b second pnumber
Returns
result of comparation
Definition at line 59 of file findRoots.cpp.
                               {
    if(fabs(a -b) < EPSILON){
        return EQUVAL;
    }
    else if(a - b > EPSILON){
        return FIRST;
    }
    return SECOND;
}
References EPSILON, EQUVAL, FIRST, and SECOND.
Referenced by findLinear(), findRoots(), rootsOrder(), and solveQuadratic().
findLinear()
roots findLinear (coef quatr)
Solve linear equation
Returns
myRoots roots of the equation
Definition at line 91 of file findRoots.cpp.
                            {
    roots myRoots{NO_ROOTS, DEFOLT, DEFOLT, DEFOLT};
    if(compare(quatr.b, 0) != 0){
        myRoots.x1 = -quatr.c/quatr.b;
        myRoots.comp = 0;
        myRoots.num = ONE_ROOT;
    }
    else if(compare(quatr.c, 0) == 0){
        myRoots.comp = 0;
        myRoots.num = INFIN_ROOTS;
    }
    else{
        myRoots.comp = 0;
        myRoots.num = NO_ROOTS;
    }
    return myRoots;
}
References coef::b, coef::c, compare(), DEFOLT, INFIN_ROOTS, NO_ROOTS, ONE_ROOT, and roots::x1.
Referenced by findRoots().
findRoots()
roots findRoots (struct coef quatr)
Calls the desired function to solve the equation
See also
findLinear(), solveQuadratic(), rootsOrder()
Returns
myRoots roots of the equation
Definition at line 151 of file findRoots.cpp.
                                   {
    roots myRoots{NO_ROOTS, DEFOLT, DEFOLT, DEFOLT};
    assert (&myRoots.x1 != NULL && "X1 un correct");
    assert (&myRoots.x2 != NULL);
    if (compare(quatr.a, 0) == 0) {
        myRoots = findLinear(quatr);
    }
    else if (compare(quatr.c, 0) == 0){
        myRoots.x1 = 0;
        myRoots.x2 = -quatr.b/quatr.c;
        myRoots.comp = 0;
        myRoots.num = ONE_ROOT;
    }
    else {
        myRoots = solveQuadratic(quatr);
    }
    rootsOrder(&myRoots);
    return myRoots;
}
References coef::a, coef::b, coef::c, compare(), DEFOLT, findLinear(), NO_ROOTS, ONE_ROOT, rootsOrder(), and solveQuadratic().
Referenced by main(), and oneTest().
makeCoef()
coef makeCoef (float a, float b, float c)
Make the structure coef using parameters
Parameters
num Number of roots
x1 first root
x2 second root
comp the complex part of the roots
Returns
quatr coefficients in structure
Definition at line 26 of file findRoots.cpp.
                                         {
    coef quatr{};
    quatr.a = a;
    quatr.b = b;
    quatr.c = c;
    return quatr;
}
References coef::a.
Referenced by makeTest().
makeRoots()
roots makeRoots (int num, float x1, float x2, float comp)
Make the structure roots using parameters
Parameters
a First parameter
b second parameter
c third parameter
Returns
quatr roots in structure
Definition at line 42 of file findRoots.cpp.
                                                         {
    roots myRoots{};
    myRoots.num = num;
    myRoots.x1 = x1;
    myRoots.x2 = x2;
    myRoots.comp = comp;
    return myRoots;
}
References roots::num.
Referenced by makeTest().
rootsOrder()
void rootsOrder (roots * myRoots)
Arranges the roots in ascending order
Parameters
myRoots
Definition at line 75 of file findRoots.cpp.
                                {
    assert(myRoots != NULL);
    if(compare(myRoots->x1, myRoots->x2) == FIRST){
        float a = myRoots->x2;
        myRoots->x2 = myRoots->x1;
        myRoots->x1 = a;
    }
}
References compare(), FIRST, roots::x1, and roots::x2.
Referenced by findRoots().
solveQuadratic()
roots solveQuadratic (coef quatr)
Solve quadratic equation
Returns
myRoots roots of the equation
Definition at line 117 of file findRoots.cpp.
                                  {
    roots myRoot{NO_ROOTS, DEFOLT, DEFOLT, DEFOLT};
    int d = quatr.b * quatr.b - 4 * quatr.a * quatr.c;
    float sqrt_val = sqrt(fabs(d));
    if (compare(d, 0) == 1) {
        myRoot.x1 = (-quatr.b + sqrt_val) / (2 * quatr.a); //ошибка quatr.b
        myRoot.x2 = (-quatr.b - sqrt_val) / (2 * quatr.a);
        myRoot.comp = 0;
        myRoot.num = TWO_ROOTS;
    }
    else if (compare(d, 0) == 0) {
        myRoot.x1 = -quatr.b / (2 * quatr.a);
        myRoot.x2 = myRoot.x1;
        myRoot.comp = 0;
        myRoot.num = ONE_ROOT;
    }
    else
    {
        myRoot.x1 = -quatr.b / (4 * quatr.a); //ошибка 2 а не 4
        myRoot.x2 = myRoot.x1;
        myRoot.comp = sqrt_val / (2 * quatr.a);
        myRoot.num = TWO_ROOTS;
    }
    return myRoot;
}
References coef::a, coef::b, coef::c, compare(), DEFOLT, NO_ROOTS, ONE_ROOT, and TWO_ROOTS.
Referenced by findRoots().