D:/CodeBlocksProjects/Solver/findRoots.h File Reference
Classes
struct coef
Structure for coefficients of the quadratic equation.
struct roots
Enumerations
enum comparation { EQUVAL
, FIRST
, SECOND
 }
enum numberOfRoots { NO_ROOTS
, ONE_ROOT
, TWO_ROOTS
, INFIN_ROOTS
 }
To store the number of roots of the equation.
Functions
roots makeRoots (int, float, float, float)
coef makeCoef (float, float, float)
roots findRoots (struct coef)
int compare (float, float)
Variables
const float EPSILON = 0.000001
const float DEFOLT = 0
Enumeration Type Documentation
comparation
enum comparation
Enumerator
EQUVAL numbers are equval
FIRST the first number is greater than the second
SECOND the second number is greater than the first
Definition at line 9 of file findRoots.h.
                {
    EQUVAL,
    FIRST,
    SECOND
};
numberOfRoots
enum numberOfRoots
To store the number of roots of the equation.
Enumerator
NO_ROOTS
ONE_ROOT
TWO_ROOTS
INFIN_ROOTS shows that equation has an infinite number of roots
Definition at line 16 of file findRoots.h.
                  {
    NO_ROOTS, ONE_ROOT, TWO_ROOTS,
    INFIN_ROOTS
};
Function Documentation
compare()
int compare (float a, float b)
Compare two numbers
Parameters
a First number
b second pnumber
Returns
result of comparation
Definition at line 59 of file findRoots.cpp.
                               {
    if(fabs(a -b) < EPSILON){
        return EQUVAL;
    }
    else if(a - b > EPSILON){
        return FIRST;
    }
    return SECOND;
}
References EPSILON, EQUVAL, FIRST, and SECOND.
Referenced by findLinear(), findRoots(), rootsOrder(), and solveQuadratic().
findRoots()
roots findRoots (struct coef quatr)
Calls the desired function to solve the equation
See also
findLinear(), solveQuadratic(), rootsOrder()
Returns
myRoots roots of the equation
Definition at line 151 of file findRoots.cpp.
                                   {
    roots myRoots{NO_ROOTS, DEFOLT, DEFOLT, DEFOLT};
    assert (&myRoots.x1 != NULL && "X1 un correct");
    assert (&myRoots.x2 != NULL);
    if (compare(quatr.a, 0) == 0) {
        myRoots = findLinear(quatr);
    }
    else if (compare(quatr.c, 0) == 0){
        myRoots.x1 = 0;
        myRoots.x2 = -quatr.b/quatr.c;
        myRoots.comp = 0;
        myRoots.num = ONE_ROOT;
    }
    else {
        myRoots = solveQuadratic(quatr);
    }
    rootsOrder(&myRoots);
    return myRoots;
}
References coef::a, coef::b, coef::c, compare(), DEFOLT, findLinear(), NO_ROOTS, ONE_ROOT, rootsOrder(), and solveQuadratic().
Referenced by main(), and oneTest().
makeCoef()
coef makeCoef (float a, float b, float c)
Make the structure coef using parameters
Parameters
num Number of roots
x1 first root
x2 second root
comp the complex part of the roots
Returns
quatr coefficients in structure
Definition at line 26 of file findRoots.cpp.
                                         {
    coef quatr{};
    quatr.a = a;
    quatr.b = b;
    quatr.c = c;
    return quatr;
}
References coef::a.
Referenced by makeTest().
makeRoots()
roots makeRoots (int num, float x1, float x2, float comp)
Make the structure roots using parameters
Parameters
a First parameter
b second parameter
c third parameter
Returns
quatr roots in structure
Definition at line 42 of file findRoots.cpp.
                                                         {
    roots myRoots{};
    myRoots.num = num;
    myRoots.x1 = x1;
    myRoots.x2 = x2;
    myRoots.comp = comp;
    return myRoots;
}
References roots::num.
Referenced by makeTest().
Variable Documentation
DEFOLT
const float DEFOLT = 0
Definition at line 6 of file findRoots.h.
Referenced by findLinear(), findRoots(), solveQuadratic(), and testConsole().
EPSILON
const float EPSILON = 0.000001
Definition at line 5 of file findRoots.h.
Referenced by compare().